matrix:
   include:
    - os: linux
      language: python

    - os: windows
      language: minimal
      before_install:
        - choco install python --version 3.8
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"


install:
  - pip install conan
  - pip install conan_package_tools bincrafters_package_tools
  - conan user

script:
  - python build.py
