matrix:
   include:
    - os: linux
      language: python
      cache: pip
      env: CONAN_GCC_VERSION=7 CONAN_DOCKER_IMAGE=lasote/conangcc7
      services:
        - docker

    - os: windows
      language: minimal
      before_install:
        - choco install python --version 3.8
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
      cache: pip


install:
  - pip install conan
  - pip install conan_package_tools bincrafters_package_tools
  - conan user

script:
  - python build.py
